### ISSUE TITLE
tfstate files should be commented out by default in the gitignore

### ISSUE THREAD

**Issue by julien731** [nimblehq/infrastructure-templates#11]
The problem with the current state of the `.gitignore` is that someone could forget to remove the `tfstate` file from the `.gitignore` in the case where there is no remote backend.

Instead, we should have it commented by default.

In the case where there _is_ a remote backend we just have to uncomment. This approach has the advantage of not f#@!*ng everything if we forget to uncomment the `tfstate` file; it would just be annoying.

**Comment by longnd** [comment]
close this issue as we're working on a new version for the template.
