### ISSUE TITLE
No `.gitignore` file in the generated project

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/infrastructure-templates#132]
## Issue

No `.gitignore` in the generated project

## Expected

The `.gitignore` should exist in the generated project.

## Steps to reproduce

1. generate the new template
2. Find the `.gitignore`

**Comment by hoangmirs** [comment]
It seems to be a [known issue](https://github.com/npm/npm/issues/3763)
We might try the solution renaming `.gitignore`

**Comment by hoangmirs** [comment]
Fixed in https://github.com/nimblehq/infrastructure-templates/pull/140
