### ISSUE TITLE
Implement the auto scaling for Fargate cluster

### ISSUE THREAD

**Issue by longnd** [nimblehq/infrastructure-templates#161]
## Why

Currently, we don't have auto-scaling for the Fargate cluster, each service runs with a fixed amount of tasks. It is not sufficient for the production environment.

Thus, we need to implement the auto-scaling for the Fargate clusters so it can scale up & down according to the pre-defined rules.

## Who Benefits?

- The clients who own the application
- The development squad that need to manage the infrastructure.

**Comment by hoangmirs** [comment]
This is duplicated with https://github.com/nimblehq/infrastructure-templates/issues/137

**Comment by longnd** [comment]
I didn't realize that. Closed. Thank you 🙏.
