### ISSUE TITLE
As the application, I have the advanced AWS infrastructure supports 2 environments

### ISSUE THREAD

**Issue by longnd** [nimblehq/infrastructure-templates#28]
## Why

- We usually set up the infrastructure for 2 environments: staging & production. The template should also support that.
- We can duplicate 3 main files (`main.tf`, `variables.tf`, `outputs.tf`) to 2 folders: `staging` and `production`

## Who Benefits?

Ensure the template supports 2 environments: staging & production.

**Comment by hoangmirs** [comment]
@longnd Do we need this issue anymore? As almost projects are using the same code for both staging and production, we just modify some variables for each environment.

**Comment by hoangmirs** [comment]
As we're using the same repository for all environments, I close this issue.
If we need this, we can re-open/create a new issue to track later
